# Multiple Linear Regression

In Multiple linear regression, we have more than one inputs/features/variables.

The formula used here will be something like this:
Salary = m1*YearsExperience + m2*Age + c

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
df = pd.read_csv('Salary_Data_MLR.csv')

In [4]:
df.head()

YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731
3              2.0  22.0   43525
4              2.2  22.2   39891

In [5]:
x = df[['YearsExperience', 'Age']]
y = df[['Salary']]

In [6]:
# Create and Fitting of model

model = LinearRegression().fit(x,y)
model

LinearRegression()

In [7]:
# Calculating the value of m1 an m2

model.coef_

array([[6153.35330145, 1836.01359426]])

In [9]:
# Calculating the value of y-intercept i.e c

model.intercept_

array([-6661.98719881])

In [16]:
# Calculating the predicted value at YearsExpereicnce = 1.1 and Age = 21
print(model.predict([[1.1 , 21]]))

[[38662.98691225]]


# Another approach

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [23]:
# importing module
from sklearn.linear_model import LinearRegression
# creating an object of LinearRegression class
LR = LinearRegression()
# fitting the training data
LR.fit(x_train,y_train)

LinearRegression()

In [24]:
y_prediction =  LR.predict(x_test)
y_prediction

array([[118686.60525402],
       [ 67497.80208802],
       [101581.52273219],
       [ 74585.69879684],
       [ 54833.367916  ],
       [ 58044.6977654 ]])

In [26]:
# MODEL EVALUATION
# Calculating the regression score

# importing r2_score module
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
# predicting the accuracy score
score=r2_score(y_test,y_prediction)
print('r2 socre is' ,score)
print('mean_sqrd_error is== ' + mean_squared_error(y_test,y_prediction))

r2 socre is 0.8852101657216538


TypeError: can only concatenate str (not "numpy.float64") to str

# sklearn.model_selection.train_test_split

In [30]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X
np.array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
list(y)
[0, 1, 2, 3, 4]

[0, 1, 2, 3, 4]

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print( "X_train = ", X_train)
print( "y_train = ", y_train)
print( "X_test =", X_test)

y_test
[1, 4]

X_train =  [[4 5]
 [0 1]
 [6 7]]
y_train =  [2, 0, 3]
X_test = [[2 3]
 [8 9]]


[1, 4]

In [46]:
train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]

[[0, 1, 2], [3, 4]]